### ISSUE TITLE
UI/UX

### ISSUE THREAD

**Issue by Mouiad-JRA** [pros-projects/Pro-educational-platform#1]
Find a website design so that we can start building it using React.js

**Comment by Mazen-Souda** [comment]
please check this
https://dribbble.com/shots/16433603-Naruto-Edu-Course-Platform/attachments/11043963?mode=media
@Mouiad-JRA @Ahmad-Zahloote

**Comment by Mouiad-JRA** [comment]
Ok, we will continue with that template @Mazen-Souda
