### ISSUE TITLE
Choose a U.I design 

### ISSUE THREAD

**Issue by Mouiad-JRA** [pros-projects/Pro-educational-platform#11]
You can use the net to choose a good and nice UI design

here are some good samples

1. https://dribbble.com/shots/17646996-E-learning-Web-App
2. https://www.behance.net/gallery/161267677/Course-Website-Design?tracking_source=search_projects%7Ccourse
3. https://www.pinterest.com/pin/14003448832724791/
4. https://dribbble.com/shots/19916180-Online-Course-Webapp
5. https://dribbble.com/shots/19052386-Edtech-Landing-Page
6. https://www.behance.net/gallery/156146499/E-learning-online-course-education-website?tracking_source=search_projects%7Ccourse
7. https://www.behance.net/gallery/149814943/E-learning-platform?tracking_source=search_projects%7Ccourse
8. https://dribbble.com/shots/19812232-Online-Education-Platform-Dashboard

**Comment by Ahmad-Zahloote** [comment]
this:
https://www.behance.net/gallery/149814943/E-learning-platform?tracking_source=search_projects%7Ccourse
